apiVersion: v1
kind: Service
metadata:
  name: deno-playground-frontend
  labels:
    app: frontend
spec:
  {{ if eq .Values.env "prod"}}
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    app: frontend
  {{ else }}
  type: NodePort
  ports:
  - port: 8090
    targetPort: http
    name: http
  selector:
    app: frontend
  {{ end }}
